FROM node:8.11.2

EXPOSE 3000
CMD ["yarn", "start"]

RUN mkdir -p /opt/app
WORKDIR /opt/app

COPY package.json /opt/app
COPY yarn.lock /opt/app
RUN yarn global add serve
RUN yarn install

COPY . /opt/app
RUN yarn build

CMD serve -s build