export const GET_SEARCH_REQUEST = 'GET_SEARCH_REQUEST'
export const GET_SEARCH_SUCCESS = 'GET_SEARCH_SUCCESS'
export const GET_SEARCH_FAILURE = 'GET_SEARCH_FAILURE'

export const GET_FILTER_REQUEST = 'GET_FILTER_REQUEST'
export const GET_FILTER_SUCCESS = 'GET_FILTER_SUCCESS'
export const GET_FILTER_FAILURE = 'GET_FILTER_FAILURE'
